import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  english: {
    navira: "Navira",
    welcome: "Welcome to the Platform",
    dashboard_hello: "Hello! 👋",
    dashboard_subtitle: "Choose what you'd like to learn today. Take your time — there's no rush!",
    dashboard_heading: "📚 What would you like to do?",
    tip_title: "Tip for today",
    tip_content: "Always use a password that has letters, numbers, and symbols together. It keeps your account safe!",
    simulations: "Simulations",
    quizzes: "Quizzes",
    logout: "Logout",
    selectLang: "Select Language",
    // Auth
    signup_title: "Create Your Account",
    signup_subtitle: "It only takes a minute!",
    login_title: "Welcome back! 👋",
    login_subtitle: "Please enter your details to sign in.",
    no_account: "Don't have an account yet?",
    create_new: "✨ Create a New Account",
    already_have: "Already have an account?",
    sign_in_here: "Sign in here",
    mobile_label: "Mobile Number",
    pass_label: "Password",
    btn_signin: "Sign In",
    btn_next: "Next",
    btn_back: "Back",
    btn_create: "🎉 Create Account",
    sim_desc: "Engage with state-of-the-art interactive 3D simulations.",
    quiz_desc: "Test your knowledge with challenging assessments.",
    back: "Back",
    
    // Simulations Page
    sim_hero_title: "Choose a Simulation",
    sim_hero_desc: "Learn digital skills by practicing in a safe environment.",
    mod1_title: "Secure Password Setup",
    mod1_desc: "Learn to create passwords that hackers can't guess.",
    mod2_title: "UPI Payment Simulation",
    mod2_desc: "Practice sending digital payments safely.",
    start: "Start Simulation",

    // Password Simulation
    pass_title: "Module 1: Secure Password Setup",
    enter_pass: "Create Password",
    confirm_pass: "Confirm Password",
    show: "Show",
    hide: "Hide",
    strength: "Strength",
    weak: "Weak",
    medium: "Medium",
    strong: "Strong",
    pass_match: "Passwords match",
    pass_mismatch: "Passwords do not match",
    submit: "Submit Password",
    rule_min: "At least 8 characters",
    rule_upper: "At least 1 uppercase letter",
    rule_digit: "At least 1 digit",
    rule_special: "At least 1 special character",
    suggest_min: "Please add more characters (need 8)",
    suggest_upper: "Add an UPPERCASE letter (like A, B, C)",
    suggest_digit: "Add a number (like 1, 2, 3)",
    suggest_special: "Add a symbol (like @, #, $)",
    success_pass: "Excellent! You've created a strong, secure password.",

    // UPI Simulation
    upi_title: "Module 2: UPI Payment Simulation",
    select_contact: "Select Contact",
    enter_amount: "Enter Amount",
    enter_pin: "Enter UPI PIN",
    receiver_warn: "Always check receiver name before paying.",
    pin_warn: "NEVER share your UPI PIN with anyone.",
    pay: "Pay Now",
    success_upi: "Payment Successful!",
    amount: "Amount",
    to: "To",
    phone_wallet: "My Wallet",

    // Quiz Shared
    quiz_q_of_y: "Question {{current}} of {{total}}",
    next_q: "Next Question →",
    see_results: "🏁 See My Results",
    try_again: "Try Again",
    back_to_quizzes: "← Back to Quizzes",
    quiz_complete: "Quiz Complete!",
    your_answers: "📋 Your Answers",
    score_msg_perfect: "Perfect! You're an expert!",
    score_msg_great: "Great job! You caught most scams!",
    score_msg_good: "Good effort — keep practicing!",
    score_msg_retry: "Don't worry — review and try again!",

    // Quizzes Selection Page
    quiz_hero_title: "Test Your Skills!",
    quiz_hero_desc: "Pick a topic below. Each quiz teaches you how to stay safe online in real situations.",
    quiz_topic_heading: "Choose a Quiz Topic",
    quiz_how_it_works_title: "How quizzes work",
    quiz_how_it_works_desc: "Choose the best answer. After each question you'll see exactly why the answer is right or wrong — so you learn from every attempt!",
    quiz_cat_phishing_title: "Phishing Emails",
    quiz_cat_phishing_desc: "Learn to spot fake bank emails, suspicious links & malicious attachments.",
    quiz_cat_sms_title: "SMS / UPI Spam",
    quiz_cat_sms_desc: "Detect fraud messages, fake UPI alerts and prize winning scam texts.",
    quiz_cat_deepfake_title: "Deepfake & Social Media",
    quiz_cat_deepfake_desc: "Identify manipulated images, deepfake videos and fake social profiles.",

    // Scam Simulator
    scam_hero_title: "AI Scam Simulator",
    scam_hero_desc: "Practice responding to scammers in a safe environment. Learn how to identify fraud attempts and protect your personal information.",
    mod3_title: "AI Scam Simulator",
    mod3_desc: "Identify and resist scammers in real-time chat simulations.",
    begin_sim: "Start Simulation",
    difficulty: "Difficulty",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    scam_resistance_score: "Scam Resistance Score",
    enable_voice: "Enable Voice Guidance",
    red_flags: "Red Flags",
    scam_type: "Scam Type",
    ignore_msg: "Ignore Message",
    ask_verify: "Ask for Verification",
    report_scam: "Report Scam",
    share_otp: "Share OTP (Unsafe)",
    select_scenario: "Choose a Scam Scenario",
    bank_otp_title: "Bank OTP Scam",
    bank_otp_desc: "A scammer pretends to be bank support asking for OTP verification.",
    lottery_title: "Lottery / Reward Scam",
    lottery_desc: "A scammer claims you won a prize and requests personal info.",
    delivery_title: "Delivery Scam",
    delivery_desc: "A fake delivery notification asking for payment or links.",
    friend_title: "Friend Impersonation",
    friend_desc: "Someone pretending to be a friend urgently asking for money.",
    back_to_scenarios: "Back to Scenarios",
    end_simulation: "End Simulation",
    restart_training: "Restart Training",
    new_scenario: "New Scenario",
    scam_dashboard_title: "AI Scam Simulator",
    scam_dashboard_desc: "Practice detecting online scams in a safe AI-driven conversation environment.",
    start_training: "Start Training",
    sim_over: "Simulation Over",
    type_response: "Type your response safely...",
    correct_msg: "✅ Correct!",
    incorrect_msg: "❌ Not quite — here's why:",

    // Scenario Data English
    bank_otp_initial: "Hello, this is SBI customer support. Your account will be blocked today due to suspicious activity. Please share your OTP immediately to verify your identity.",
    bank_otp_tactic: "Urgency and Authority Impersonation",
    bank_otp_rf1: "Urgent threat (blocking account)",
    bank_otp_rf2: "Request for OTP",
    bank_otp_rf3: "Unexpected contact",

    lottery_initial: "Congratulations! You have won a cash prize of ₹25,00,000 in the KBC Lucky Draw. To claim your prize, please send your Aadhaar card photo and bank details.",
    lottery_tactic: "Greed and Excitement",
    lottery_rf1: "Too good to be true",
    lottery_rf2: "Request for sensitive personal documents",
    lottery_rf3: "Unknown source",

    delivery_initial: "Your package is held at our warehouse due to an incomplete address. Please click this link to update your details or pay ₹5 for re-delivery: www.amazn-delivery-fix.com",
    delivery_tactic: "Curiosity and Low Stakes (Small Amount)",
    delivery_rf1: "Suspicious link (misspelled URL)",
    delivery_rf2: "Small payment for re-delivery",
    delivery_rf3: "Vague package info",

    friend_initial: "Hey, it's me! I'm in a huge trouble. I'm at the hospital with a friend and my UPI is not working. Can you please send ₹2,000 urgently? I'll pay you back tonight.",
    friend_tactic: "Emotional Manipulation and Panic",
    friend_rf1: "Urgent money request",
    friend_rf2: "Claims emergency",
    friend_rf3: "Unusual communication method",
  },
  hindi: {
    navira: "Navira",
    welcome: "प्लेटफ़ॉर्म पर आपका स्वागत है",
    dashboard_hello: "नमस्ते! 👋",
    dashboard_subtitle: "चुनें कि आज आप क्या सीखना चाहते हैं। अपना समय लें — कोई जल्दी नहीं है!",
    dashboard_heading: "📚 आप क्या करना चाहेंगे?",
    tip_title: "आज का सुझाव",
    tip_content: "हमेशा ऐसा पासवर्ड इस्तेमाल करें जिसमें अक्षर, अंक और विशेष चिह्न (symbols) एक साथ हों। यह आपके खाते को सुरक्षित रखता है!",
    simulations: "सिम्युलेशन्स",
    quizzes: "क्विझ",
    logout: "लॉग आउट",
    selectLang: "भाषा चुनें",
    // Auth
    signup_title: "अपना खाता बनाएं",
    signup_subtitle: "इसमें केवल एक मिनट लगता है!",
    login_title: "वापसी पर स्वागत है! 👋",
    login_subtitle: "कृपया साइन इन करने के लिए अपना विवरण दर्ज करें।",
    no_account: "क्या आपके पास अभी तक खाता नहीं है?",
    create_new: "✨ एक नया खाता बनाएं",
    already_have: "क्या आपके पास पहले से खाता है?",
    sign_in_here: "यहाँ साइन इन करें",
    mobile_label: "मोबाइल नंबर",
    pass_label: "पासवर्ड",
    btn_signin: "साइन इन करें",
    btn_next: "अगला",
    btn_back: "पीछे",
    btn_create: "🎉 खाता बनाएं",
    sim_desc: "अत्याधुनिक इंटरैक्टिव 3D simulations के साथ जुड़ें।",
    quiz_desc: "चुनौतीपूर्ण assessments के साथ अपने ज्ञान का परीक्षण करें।",
    back: "पीछे",

    // Simulations Page
    sim_hero_title: "एक Simulation चुनें",
    sim_hero_desc: "सुरक्षित वातावरण में अभ्यास करके डिजिटल कौशल सीखें।",
    mod1_title: "Secure Password Setup",
    mod1_desc: "ऐसे पासवर्ड बनाना सीखें जिन्हें हैकर्स अनुमान न लगा सकें।",
    mod2_title: "UPI Payment Simulation",
    mod2_desc: "सुरक्षित रूप से डिजिटल भुगतान भेजने का अभ्यास करें।",
    start: "Simulation शुरू करें",

    // Password Simulation
    pass_title: "Module 1: Secure Password Setup",
    enter_pass: "पासवर्ड बनाएं",
    confirm_pass: "पासवर्ड की पुष्टि करें",
    show: "देखें",
    hide: "छिपाएं",
    strength: "शक्ति",
    weak: "कमजोर",
    medium: "मध्यम",
    strong: "मजबूत",
    pass_match: "पासवर्ड मेल खाते हैं",
    pass_mismatch: "पासवर्ड मेल नहीं खाते",
    submit: "पासवर्ड जमा करें",
    rule_min: "कम से कम 8 अक्षर",
    rule_upper: "कम से कम 1 बड़ा अक्षर (ABC)",
    rule_digit: "कम से कम 1 अंक (123)",
    rule_special: "कम से कम 1 विशेष वर्ण (@#$)",
    suggest_min: "कृपया और अक्षर जोड़ें (8 की आवश्यकता है)",
    suggest_upper: "एक बड़ा अक्षर (A, B, C) जोड़ें",
    suggest_digit: "एक अंक (1, 2, 3) जोड़ें",
    suggest_special: "एक विशेष वर्ण (@, #, $) जोड़ें",
    success_pass: "बहुत बढ़िया! आपने एक मजबूत और सुरक्षित पासवर्ड बनाया है।",

    // UPI Simulation
    upi_title: "Module 2: UPI Payment Simulation",
    select_contact: "संपर्क चुनें",
    enter_amount: "राशि दर्ज करें",
    enter_pin: "UPI PIN दर्ज करें",
    receiver_warn: "भुगतान करने से पहले हमेशा प्राप्तकर्ता का नाम जांचें।",
    pin_warn: "कभी भी अपना UPI PIN किसी के साथ साझा न करें।",
    pay: "अभी भुगतान करें",
    success_upi: "भुगतान सफल रहा!",
    amount: "राशि",
    to: "को",
    phone_wallet: "मेरा वॉलेट",

    // Quiz Shared
    quiz_q_of_y: "प्रश्न {{current}} का {{total}}",
    next_q: "अगला प्रश्न →",
    see_results: "🏁 मेरा परिणाम देखें",
    try_again: "फिर से कोशिश करें",
    back_to_quizzes: "← क्विज़ पर वापस जाएं",
    quiz_complete: "क्विज़ पूरा हुआ!",
    your_answers: "📋 आपके उत्तर",
    score_msg_perfect: "शानदार! आप एक विशेषज्ञ हैं!",
    score_msg_great: "बहुत अच्छा! आपने अधिकांश घोटालों को पहचाना!",
    score_msg_good: "अच्छा प्रयास — अभ्यास जारी रखें!",
    score_msg_retry: "चिंता न करें — समीक्षा करें और पुनः प्रयास करें!",

    // Quizzes Selection Page
    quiz_hero_title: "अपने कौशल का परीक्षण करें!",
    quiz_hero_desc: "नीचे एक विषय चुनें। प्रत्येक क्विज़ आपको वास्तविक स्थितियों में सुरक्षित रहने का तरीका सिखाती है।",
    quiz_topic_heading: "एक प्रश्नोत्तरी विषय चुनें",
    quiz_how_it_works_title: "क्विज़ कैसे काम करते हैं",
    quiz_how_it_works_desc: "सबसे अच्छा उत्तर चुनें। प्रत्येक प्रश्न के बाद आप देखेंगे कि उत्तर सही या गलत क्यों है — ताकि आप हर प्रयास से सीखें!",
    quiz_cat_phishing_title: "फिशिंग ईमेल",
    quiz_cat_phishing_desc: "नकली बैंक ईमेल, संदिग्ध लिंक और हानिकारक अटैचमेंट को पहचानना सीखें।",
    quiz_cat_sms_title: "एसएमएस / यूपीआई स्पैम",
    quiz_cat_sms_desc: "धोखाधड़ी संदेशों, नकली यूपीआई अलर्ट और पुरस्कार जीतने वाले घोटाले संदेशों का पता लगाएं।",
    quiz_cat_deepfake_title: "डीपफेक और सोशल मीडिया",
    quiz_cat_deepfake_desc: "हेरफेर की गई छवियों, डीपफेक वीडियो और नकली सोशल प्रोफाइल की पहचान करें।",

    // Scam Simulator
    scam_hero_title: "एआय स्कैम सिम्युलेटर",
    scam_hero_desc: "सुरक्षित वातावरण में स्कैमर्स को जवाब देने का अभ्यास करें। धोखाधड़ी के प्रयासों की पहचान करना और अपनी व्यक्तिगत जानकारी की रक्षा करना सीखें।",
    mod3_title: "एआय स्कैम सिम्युलेटर",
    mod3_desc: "रीयल-टाइम चैट सिम्युलेशन्स में स्कैमर्स को पहचानें और उनका विरोध करें।",
    begin_sim: "सिम्युलेशन शुरू करें",
    difficulty: "कठिनाई",
    beginner: "शुरुआती",
    intermediate: "मध्यम",
    advanced: "उन्नत",
    scam_resistance_score: "स्कैम प्रतिरोध स्कोर",
    enable_voice: "वॉयस गाइडेंस सक्षम करें",
    red_flags: "खतरे के संकेत",
    scam_type: "स्कैम का प्रकार",
    ignore_msg: "संदेश अनदेखा करें",
    ask_verify: "सत्यापन मांगें",
    report_scam: "स्कैम की रिपोर्ट करें",
    share_otp: "ओटीपी (OTP) साझा करें (असुरक्षित)",
    select_scenario: "एक स्कैम परिदृश्य चुनें",
    bank_otp_title: "बैंक ओटीपी स्कैम",
    bank_otp_desc: "एक स्कैमर बैंक सपोर्ट होने का नाटक करता है और ओटीपी मांगता है।",
    lottery_title: "लॉटरी / इनाम स्कैम",
    lottery_desc: "एक स्कैमर दावा करता है कि आपने इनाम जीता है और व्यक्तिगत जानकारी मांगता है।",
    delivery_title: "डिलीवरी स्कैम",
    delivery_desc: "एक फर्जी डिलीवरी सूचना जिसमें भुगतान या लिंक मांगा जाता है।",
    friend_title: "मित्र प्रतिरूपण",
    friend_desc: "कोई मित्र होने का नाटक करता है और तत्काल पैसे मांगता है।",
    back_to_scenarios: "परिदृश्यों पर वापस जाएं",
    end_simulation: "सिम्युलेशन समाप्त करें",
    restart_training: "प्रशिक्षण पुनरारंभ करें",
    new_scenario: "नया परिदृश्य",
    scam_dashboard_title: "एआय स्कैम सिम्युलेटर",
    scam_dashboard_desc: "सुरक्षित एआय-आधारित बातचीत के माहौल में ऑनलाइन घोटालों का पता लगाने का अभ्यास करें।",
    start_training: "प्रशिक्षण शुरू करें",
    sim_over: "सिम्युलेशन समाप्त",
    type_response: "अपना उत्तर सुरक्षित रूप से टाइप करें...",
    correct_msg: "✅ सही!",
    incorrect_msg: "❌ बिल्कुल नहीं — यहाँ कारण बताया गया है:",

    // Scenario Data Hindi
    bank_otp_initial: "नमस्ते, यह एसबीआई (SBI) ग्राहक सहायता है। संदिग्ध गतिविधि के कारण आपका खाता आज ब्लॉक कर दिया जाएगा। कृपया अपनी पहचान सत्यापित करने के लिए तुरंत अपना ओटीपी (OTP) साझा करें।",
    bank_otp_tactic: "जल्दबाजी और अधिकार का प्रतिरूपण (Urgency & Authority)",
    bank_otp_rf1: "तत्काल धमकी (खाता ब्लॉक करना)",
    bank_otp_rf2: "ओटीपी (OTP) मांगना",
    bank_otp_rf3: "अप्रत्याशित संपर्क",

    lottery_initial: "बधाई हो! आपने KBC लकी ड्रॉ में ₹25,00,000 का नकद पुरस्कार जीता है। अपना पुरस्कार प्राप्त करने के लिए, कृपया अपना आधार कार्ड का फोटो और बैंक विवरण भेजें।",
    lottery_tactic: "लालच और उत्साह",
    lottery_rf1: "सच होने के लिए बहुत अच्छा लगता है",
    lottery_rf2: "संवेदनशील व्यक्तिगत दस्तावेजों का अनुरोध",
    lottery_rf3: "अज्ञात स्रोत",

    delivery_initial: "अधूरे पते के कारण आपका पैकेज हमारे गोदाम में रोका गया है। कृपया अपना विवरण अपडेट करने के लिए इस लिंक पर क्लिक करें या पुनः डिलीवरी के लिए ₹5 का भुगतान करें: www.amazn-delivery-fix.com",
    delivery_tactic: "जिज्ञासा और कम जोखिम (छोटी राशि)",
    delivery_rf1: "संदिग्ध लिंक (गलत यूआरएल)",
    delivery_rf2: "पुनः डिलीवरी के लिए छोटा भुगतान",
    delivery_rf3: "पैकेज की अस्पष्ट जानकारी",

    friend_initial: "अरे, यह मैं हूँ! मैं एक बहुत बड़ी मुसीबत में हूँ। मैं एक दोस्त के साथ अस्पताल में हूँ और मेरा यूपीआई (UPI) काम नहीं कर रहा है। क्या आप कृपया तुरंत ₹2,000 भेज सकते हैं? मैं आपको आज रात वापस कर दूंगा।",
    friend_tactic: "भावनात्मक हेरफेर और घबराहट",
    friend_rf1: "तत्काल पैसे का अनुरोध",
    friend_rf2: "आपातकाल का दावा",
    friend_rf3: "संचार का असामान्य तरीका",
  },
  marathi: {
    navira: "Navira",
    welcome: "प्लॅटफॉर्मवर आपले स्वागत आहे",
    dashboard_hello: "नमस्कार! 👋",
    dashboard_subtitle: "आज तुम्हाला काय शिकायला आवडेल ते निवडा. आरामात शिका — कोणतीही घाई नाही!",
    dashboard_heading: "📚 तुम्हाला काय करायला आवडेल?",
    tip_title: "आजचा सल्ला",
    tip_content: "नेहमी असा पासवर्ड वापरा ज्यामध्ये अक्षरे, अंक आणि विशेष चिन्हे (symbols) एकत्रित असतील. यामुळे तुमचे खाते सुरक्षित राहते!",
    simulations: "सिम्युलेशन्स",
    quizzes: "क्विझ",
    logout: "लॉग आउट",
    selectLang: "भाषा निवडा",
    // Auth
    signup_title: "तुमचे खाते तयार करा",
    signup_subtitle: "याला फक्त एक मिनिट लागतो!",
    login_title: "पुन्हा स्वागत आहे! 👋",
    login_subtitle: "कृपया साइन इन करण्यासाठी तुमचे तपशील भरा.",
    no_account: "अद्याप खाते नाही?",
    create_new: "✨ नवीन खाते तयार करा",
    already_have: "तुमचे आधीच खाते आहे का?",
    sign_in_here: "येथे साइन इन करा",
    mobile_label: "मोबाईल नंबर",
    pass_label: "पासवर्ड",
    btn_signin: "साइन इन करा",
    btn_next: "पुढे",
    btn_back: "मागे",
    btn_create: "🎉 खाते तयार करा",
    sim_desc: "अत्याधुनिक संवादात्मक 3D simulations सह व्यस्त रहा.",
    quiz_desc: "आव्हानात्मक assessments द्वारे आपल्या ज्ञानाची चाचणी घ्या.",
    back: "मागे",

    // Simulations Page
    sim_hero_title: "एक Simulation निवडा",
    sim_hero_desc: "सुरक्षित वातावरणात सराव करून डिजिटल कौशल्ये शिका.",
    mod1_title: "Secure Password Setup",
    mod1_desc: "हॅकर्स ओळखू शकणार नाहीत असे पासवर्ड तयार करायला शिका.",
    mod2_title: "UPI Payment Simulation",
    mod2_desc: "सुरक्षितपणे डिजिटल पेमेंट पाठवण्याचा सराव करा.",
    start: "Simulation सुरू करा",

    // Password Simulation
    pass_title: "Module 1: Secure Password Setup",
    enter_pass: "पासवर्ड तयार करा",
    confirm_pass: "पासवर्डची पुष्टी करा",
    show: "दाखवा",
    hide: "लपवा",
    strength: "शक्ती",
    weak: "कमकुवत",
    medium: "मध्यम",
    strong: "मजबूत",
    pass_match: "पासवर्ड जुळतात",
    pass_mismatch: "पासवर्ड जुळत नाहीत",
    submit: "पासवर्ड सबमिट करा",
    rule_min: "किमान 8 अक्षरे",
    rule_upper: "किमान 1 मोठे अक्षर (ABC)",
    rule_digit: "किमान 1 अंक (123)",
    rule_special: "किमान 1 विशेष वर्ण (@#$)",
    suggest_min: "कृपया अधिक अक्षरे जोडा (8 आवश्यक आहेत)",
    suggest_upper: "मोठे अक्षर (A, B, C) जोडा",
    suggest_digit: "एक अंक (1, 2, 3) जोडा",
    suggest_special: "विशेष वर्ण (@, #, $) जोडा",
    success_pass: "उत्कृष्ट! तुम्ही एक मजबूत आणि सुरक्षित पासवर्ड तयार केला आहे.",

    // UPI Simulation
    upi_title: "Module 2: UPI Payment Simulation",
    select_contact: "संपर्क निवडा",
    enter_amount: "रक्कम टाका",
    enter_pin: "UPI PIN टाका",
    receiver_warn: "पेमेंट करण्यापूर्वी नेहमी प्राप्तकर्त्याचे नाव तपासा.",
    pin_warn: "तुमचा UPI PIN कधीही कोणाशीही शेअर करू नका.",
    pay: "आताच पेमेंट करा",
    success_upi: "पेमेंट यशस्वी झाले!",
    amount: "रक्कम",
    to: "ला",
    phone_wallet: "माझे वॉलेट",

    // Quiz Shared
    quiz_q_of_y: "प्रश्न {{current}} पैकी {{total}}",
    next_q: "पुढील प्रश्न →",
    see_results: "🏁 माझे निकाल पहा",
    try_again: "पुन्हा प्रयत्न करा",
    back_to_quizzes: "← क्विझवर परत जा",
    quiz_complete: "क्विझ पूर्ण झाली!",
    your_answers: "📋 तुमची उत्तरे",
    score_msg_perfect: "उत्कृष्ट! तुम्ही तज्ञ आहात!",
    score_msg_great: "छान! तुम्ही बहुतेक फसवणुकी ओळखल्यात!",
    score_msg_good: "चांगले प्रयत्न — सराव करत राहा!",
    score_msg_retry: "काळजी करू नका — पुन्हा प्रयत्न करा!",

    // Quizzes Selection Page
    quiz_hero_title: "तुमच्या कौशल्याची चाचणी घ्या!",
    quiz_hero_desc: "खालीलपैकी एक विषय निवडा. प्रत्येक क्विझ तुम्हाला वास्तविक परिस्थितीत ऑनलाइन सुरक्षित कसे राहायचे ते शिकवते.",
    quiz_topic_heading: "एक क्विझ विषय निवडा",
    quiz_how_it_works_title: "क्विझ कशा प्रकारे काम करतात",
    quiz_how_it_works_desc: "सर्वोत्तम उत्तर निवडा. प्रत्येक प्रश्नानंतर तुम्हाला उत्तर बरोबर किंवा चुकीचे का आहे हे कळेल — जेणेकरून तुम्ही प्रत्येक वेळी काहीतरी नवीन शिकाल!",
    quiz_cat_phishing_title: "फिशिंग ईमेल",
    quiz_cat_phishing_desc: "खोटे बँक ईमेल, संशयास्पद लिंक्स आणि घातक फाईल्स ओळखायला शिका.",
    quiz_cat_sms_title: "एसएमएस / यूपीआई स्पॅम",
    quiz_cat_sms_desc: "फसव्या मेसेज, खोट्या युपीआय अलर्ट आणि बक्षीस जिंकल्याच्या फसव्या संदेशांचा शोध घ्या.",
    quiz_cat_deepfake_title: "डीपफेक आणि सोशल मीडिया",
    quiz_cat_deepfake_desc: "बदललेले फोटो, डीपफेक व्हिडीओ आणि खोट्या सोशल प्रोफाईल्स ओळखा.",

    // Scam Simulator
    scam_hero_title: "एआय स्कॅम सिम्युलेटर",
    scam_hero_desc: "सुरक्षित वातावरणात स्कॅमर्सना प्रतिसाद देण्याचा सराव करा. फसवणुकीचे प्रयत्न ओळखायला आणि आपल्या वैयक्तिक माहितीचे रक्षण करायला शिका.",
    mod3_title: "एआय स्कॅम सिम्युलेटर",
    mod3_desc: "रिअल-टाइम चॅट सिम्युलेशन्समध्ये स्कॅमर्स ओळखा आणि त्यांना विरोध करा.",
    begin_sim: "सिम्युलेशन सुरू करा",
    difficulty: "काठिण्य पातळी",
    beginner: "नवशिक्या",
    intermediate: "मध्यम",
    advanced: "प्रगत",
    scam_resistance_score: "स्कॅम प्रतिकार स्कोअर",
    enable_voice: "व्हॉइस गाइडन्स सुरू करा",
    red_flags: "धोक्याचे संकेत",
    scam_type: "स्कॅमचा प्रकार",
    ignore_msg: "संदेश दुर्लक्षित करा",
    ask_verify: "पडताळणी विचारा",
    report_scam: "स्कॅमची तक्रार करा",
    share_otp: "ओटीपी शेअर करा (असुरक्षित)",
    select_scenario: "एक स्कॅम परिस्थिती निवडा",
    bank_otp_title: "बँक ओटीपी स्कॅम",
    bank_otp_desc: "एक स्कॅमर बँक सपोर्ट असल्याचे भासवून ओटीपी मागतो.",
    lottery_title: "लॉटरी / बक्षीस स्कॅम",
    lottery_desc: "एक स्कॅमर दावा करतो की तुम्ही बक्षीस जिंकले आहे आणि वैयक्तिक माहिती मागतो.",
    delivery_title: "डिलीवरी स्कॅम",
    delivery_desc: "एक बनावट डिलीवरी सूचना ज्यामध्ये पेमेंट किंवा लिंक विचारली जाते.",
    friend_title: "मित्राचे सोंग",
    friend_desc: "कोणीतरी मित्र असल्याचे भासवून तातडीने पैसे मागतो.",
    back_to_scenarios: "परिस्थितीवर परत जा",
    end_simulation: "सिम्युलेशन समाप्त करा",
    restart_training: "प्रशिक्षण पुन्हा सुरू करा",
    new_scenario: "नवीन परिस्थिती",
    scam_dashboard_title: "एआय स्कॅम सिम्युलेटर",
    scam_dashboard_desc: "सुरक्षित एआय-आधारित संभाषणाच्या वातावरणात ऑनलाइन घोटाळे ओळखण्याचा सराव करा.",
    start_training: "प्रशिक्षण सुरू करा",
    sim_over: "सिम्युलेशन समाप्त",
    type_response: "तुमचे उत्तर सुरक्षितपणे टाईप करा...",
    correct_msg: "✅ बरोबर!",
    incorrect_msg: "❌ अगदी बरोबर नाही — याचे कारण असे आहे:",

    // Scenario Data Marathi
    bank_otp_initial: "नमस्कार, मी SBI कस्टमर सपोर्टमधून बोलत आहे. संशयास्पद हालचालींमुळे तुमचे खाते आज ब्लॉक केले जाईल. तुमची ओळख पडताळण्यासाठी कृपया त्वरित तुमचा OTP शेअर करा.",
    bank_otp_tactic: "घाई आणि अधिकाराचे सोंग (Urgency & Authority)",
    bank_otp_rf1: "तातडीची धमकी (खाते ब्लॉक करणे)",
    bank_otp_rf2: "OTP ची मागणी",
    bank_otp_rf3: "अनपेक्षित संपर्क",

    lottery_initial: "अभिनंदन! तुम्ही KBC लकी ड्रॉमध्ये ₹25,00,000 चे रोख बक्षीस जिंकले आहे. तुमचे बक्षीस मिळवण्यासाठी कृपया तुमच्या आधार कार्डचा फोटो आणि बँक तपशील पाठवा.",
    lottery_tactic: "लोभ आणि उत्साह",
    lottery_rf1: "खरे वाटणार नाही असे आमिष",
    lottery_rf2: "संवेदनशील वैयक्तिक कागदपत्रांची मागणी",
    lottery_rf3: "अज्ञात स्रोत",

    delivery_initial: "अपूर्ण पत्त्यामुळे तुमचे पार्सल आमच्या गोदामात अडकले आहे. कृपया तुमचे तपशील अपडेट करण्यासाठी या लिंकवर क्लिक करा किंवा पुन्हा डिलिव्हरीसाठी ₹5 भरा: www.amazn-delivery-fix.com",
    delivery_tactic: "उत्सुकता आणि कमी धोका (लहान रक्कम)",
    delivery_rf1: "संशयास्पद लिंक (चुकीची URL)",
    delivery_rf2: "पुन्हा डिलिव्हरीसाठी लहान पेमेंट",
    delivery_rf3: "पार्सलची अस्पष्ट माहिती",

    friend_initial: "अरे, मी आहे! मी एका मोठ्या अडचणीत आहे. मी मित्रासोबत हॉस्पिटलमध्ये आहे आणि माझा UPI काम करत नाहीये. कृपया तू तातडीने ₹2,000 पाठवू शकतोस का? मी आज रात्री तुला परत करेन.",
    friend_tactic: "भावनिक हाताळणी आणि भीती",
    friend_rf1: "तातडीने पैशांची मागणी",
    friend_rf2: "आणीबाणीचा दावा",
    friend_rf3: "संवादाचा असामान्य मार्ग",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('language') || 'english');

  useEffect(() => {
    localStorage.setItem('language', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || translations['english'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
